### ISSUE TITLE
the feed's url return an issue

### ISSUE THREAD

**Issue by zpartakov** [imorland/syndication#14]
```
Deprecated: str_getcsv(): Passing null to parameter #1 ($string) of type string is deprecated in /home/clients/sites/gulu-unige.ch/forum/vendor/flarum/core/src/Search/GambitManager.php on line 67

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /home/clients/sites/gulu-unige.ch/forum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:20 
Stack trace: #0 /home/clients/sites/gulu-unige.ch/forum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(42): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent() 
#1 /home/clients/sites/gulu-unige.ch/forum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(21): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() 
#2 /home/clients/sites/gulu-unige.ch/forum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(75): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit(Object(Laminas\Diactoros\Response)) 
#3 /home/clients/sites/gulu-unige.ch/forum/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() 
#4 /home/clients/sites/gulu-unige.ch/forum/public/index.php(26): Flarum\Http\Server->listen() 
#5 {main} thrown in /home/clients/sites/gulu-unige.ch/forum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 20
```

**Comment by imorland** [comment]
Thanks for the report.

The root cause is the deprecation notice in the first line of the trace:

> Deprecated: str_getcsv(): Passing null to parameter #1 ($string) of type string is deprecated in .../Flarum/Search/GambitManager.php on line 67

On PHP 8.1+, passing `null` to `str_getcsv()` emits a deprecation. Once PHP outputs that notice as HTML to the response stream, the real XML response can't be emitted ("Output has been emitted previously"), hence the `EmitterException`.

Why it was reaching `GambitManager` with `null`: our controller was calling the `/discussions` API with `filter[q] = null` whenever no search term was present. Flarum core's `DiscussionSearcher` then passed that null straight through to `GambitManager::explode()` → `str_getcsv(null, ' ')`.

Fixed in 9784f20 (PR #20), which conditionally includes `filter[q]` in the API call only when there is an actual search term. PR #21 added a PHPUnit integration test for `/rss/discussions` without any filter/search on PHP 8.1/8.3/8.5 to prevent regression.

Closing — please reopen if you still see this after updating to the next release.
