### ISSUE TITLE
TypeError: AbstractFeedController::getRelationship

### ISSUE THREAD

**Issue by iPurpl3x** [imorland/syndication#9]
I found this error multiple times in our logs:

```log
[2022-10-03 00:55:43] flarum.ERROR: TypeError: IanM\FlarumFeeds\Controller\AbstractFeedController::getRelationship(): Argument #2 ($relationship) must be of type stdClass, null given, called in /opt/flarum/vendor/ianm/syndication/src/Controller/DiscussionFeedController.php on line 105 and defined in /opt/flarum/vendor/ianm/syndication/src/Controller/AbstractFeedController.php:212
Stack trace:
#0 /opt/flarum/vendor/ianm/syndication/src/Controller/DiscussionFeedController.php(105): IanM\FlarumFeeds\Controller\AbstractFeedController->getRelationship()
#1 /opt/flarum/vendor/ianm/syndication/src/Controller/AbstractFeedController.php(124): IanM\FlarumFeeds\Controller\DiscussionFeedController->getFeedContent()
#2 /opt/flarum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): IanM\FlarumFeeds\Controller\AbstractFeedController->handle()
#3 /opt/flarum/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#4 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#5 /opt/flarum/vendor/glowingblue/localizd/src/Middleware/RegisterMiddleware.php(82): Laminas\Stratigility\Next->handle()
#6 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): GlowingBlue\Localizd\Middleware\RegisterMiddleware->process()
#7 /opt/flarum/vendor/glowingblue/product-picker/src/Middleware/AddProductFilter.php(40): Laminas\Stratigility\Next->handle()
#8 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): GlowingBlue\ProductPicker\Middleware\AddProductFilter->process()
#9 /opt/flarum/vendor/fof/frontpage/src/Middleware/AddFrontpageFilter.php(30): Laminas\Stratigility\Next->handle()
#10 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\FrontPage\Middleware\AddFrontpageFilter->process()
#11 /opt/flarum/vendor/glowingblue/core/src/Middleware/FilteringRequestMiddleware.php(33): Laminas\Stratigility\Next->handle()
#12 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): GlowingBlue\Core\Middleware\FilteringRequestMiddleware->process()
#13 /opt/flarum/vendor/fof/discussion-language/src/Middleware/AddLanguageFilter.php(32): Laminas\Stratigility\Next->handle()
#14 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\DiscussionLanguage\Middleware\AddLanguageFilter->process()
#15 /opt/flarum/vendor/fof/terms/src/Middlewares/RegisterMiddleware.php(59): Laminas\Stratigility\Next->handle()
#16 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\Terms\Middlewares\RegisterMiddleware->process()
#17 /opt/flarum/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#18 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#19 /opt/flarum/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#20 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#21 /opt/flarum/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#22 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#23 /opt/flarum/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#24 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#25 /opt/flarum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#26 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#27 /opt/flarum/vendor/glowingblue/core/src/Middleware/RedirectsMiddleware.php(53): Laminas\Stratigility\Next->handle()
#28 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): GlowingBlue\Core\Middleware\RedirectsMiddleware->process()
#29 /opt/flarum/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#30 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#31 /opt/flarum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#32 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#33 /opt/flarum/vendor/glowingblue/gamilytics/src/Middleware/RecordActiveTimeMiddleware.php(39): Laminas\Stratigility\Next->handle()
#34 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): GlowingBlue\Gamilytics\Middleware\RecordActiveTimeMiddleware->process()
#35 /opt/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#36 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#37 /opt/flarum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#38 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#39 /opt/flarum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#40 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#41 /opt/flarum/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#42 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CollectGarbage->process()
#43 /opt/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#44 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#45 /opt/flarum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#46 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#47 /opt/flarum/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#48 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#49 /opt/flarum/vendor/fof/merge-discussions/src/Middleware/Redirection.php(28): Laminas\Stratigility\Next->handle()
#50 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\MergeDiscussions\Middleware\Redirection->process()
#51 /opt/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#52 /opt/flarum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#53 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#54 /opt/flarum/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#55 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#56 /opt/flarum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#57 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#58 /opt/flarum/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#59 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#60 /opt/flarum/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#61 /opt/flarum/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#62 /opt/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#63 /opt/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#64 /opt/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#65 /opt/flarum/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#66 /opt/flarum/public/index.php(26): Flarum\Http\Server->listen()
#67 {main}  
```

**Comment by iPurpl3x** [comment]
Oh, sorry, I guess this has been fixed in #8. I didn't install the latest update.
